export {default as PayMethod} from './PayMethod'
export {default as ChangePatient} from './ChangePatient'
export {default as TipTextBar} from './TipTextBar'
export {default as StatusCell} from './StatusCell'
export {default as CusCell} from './CusCell'
export {default as EmptyPage} from './TipPage/EmptyPage'
export {default as Copyright} from './Copyright'
